#!/usr/bin/env node
/**
 * build_search_index.js — regenerates js/data/search-index.js, the
 * lightweight site-wide search index used for cross-page search.
 *
 * Run this locally (not part of the site's runtime) any time you add,
 * rename, or remove a nodegroup in any js/data/*.js file:
 *
 *     node scripts/build_search_index.js
 *
 * How it works: it actually executes every js/data/*.js file (except the
 * index itself) in a sandboxed `window.NODEGROUPS = []` context, the same
 * way the browser does across <script src> tags — so it can't get out of
 * sync with whatever fields/shape your nodegroup objects actually use.
 * It then writes out a tiny id/name/category/sub/tagline/description/href
 * record per nodegroup — no images, so this file stays cheap to load on
 * every page regardless of how many screenshots or GIFs the pack grows to.
 *
 * No npm install needed — uses only Node's built-in `vm` module.
 */

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.join(__dirname, "..");
const DATA_DIR = path.join(ROOT, "js", "data");
const OUT_FILE = path.join(DATA_DIR, "search-index.js");

const files = fs
  .readdirSync(DATA_DIR)
  .filter((f) => f.endsWith(".js") && f !== "search-index.js")
  .sort();

if (!files.length) {
  console.error(`No js/data/*.js files found in ${DATA_DIR}`);
  process.exit(1);
}

const sandbox = { window: { NODEGROUPS: [] }, console };
vm.createContext(sandbox);

files.forEach((file) => {
  const code = fs.readFileSync(path.join(DATA_DIR, file), "utf8");
  try {
    vm.runInContext(code, sandbox, { filename: file });
  } catch (err) {
    console.error(`Failed to execute ${file}: ${err.message}`);
    process.exit(1);
  }
});

const nodegroups = sandbox.window.NODEGROUPS;

const missingIds = nodegroups.filter((n) => !n.id || !n.category || !n.name);
if (missingIds.length) {
  console.error(
    `${missingIds.length} nodegroup(s) are missing id/category/name — fix these before regenerating:`,
    missingIds
  );
  process.exit(1);
}

const index = nodegroups.map((n) => ({
  id: n.id,
  name: n.name,
  category: n.category,
  sub: n.sub || null,
  tagline: n.tagline || "",
  description: n.description || "",
  href: `${n.category}.html#${n.id}`,
}));

const banner = `/* AUTO-GENERATED by scripts/build_search_index.js — do not hand-edit.
   Regenerate any time you add/rename/remove a nodegroup in js/data/*.js:
     node scripts/build_search_index.js
   Lightweight site-wide index (no images) used for cross-page search —
   loaded on every page, before app.js. See js/app.js's initSearch(). */
`;
const body = `window.SEARCH_INDEX = ${JSON.stringify(index, null, 2)};\n`;

fs.writeFileSync(OUT_FILE, banner + body);
console.log(`Wrote ${index.length} entries from ${files.length} file(s) to js/data/search-index.js`);
